# Use Python3 flex environment
runtime: python37
env: flex

# Run gunicorn on app object in app.py
entrypoint: gunicorn -b :$PORT app:app

#env_variables:
#    CLOUD_STORAGE_BUCKET: icsfinalbucket

# Spin up 2 instances
manual_scaling:
  instances: 2

# Use an f1-micro machine type
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
